manager:
  args:
    max_rounds: 10
    win_conditions:
      - StudentCorrect
game:
  name: mathquiz
  players:
    - name: mathquiz_teacher
      args:
        id: gpt4 teacher
        roles: 
          - TeacherGenerateQuestion
          - TeacherAnswerQuestion
        lm:
          type: AzureOpenAI
          args:
            api_base: https://allam-swn-gpt-01.openai.azure.com/
            api_version: 2023-07-01-preview
            deployment_id: gpt-4o-900ptu
            max_tokens: 800
            temperature: 0.8
            top_p: 0.95
            frequency_penalty: 0
            presence_penalty: 0
    - name: mathquiz_student
      args:
        id: gpt4 student
        roles: 
          - StudentAnswerQuestion
        lm:
          type: AzureOpenAI
          args:
            api_base: https://allam-swn-gpt-01.openai.azure.com/
            api_version: 2023-07-01-preview
            deployment_id: gpt-4o-900ptu
            max_tokens: 800
            temperature: 0.8
            top_p: 0.95
            frequency_penalty: 0
            presence_penalty: 0
